# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-24 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotterydraw',
            name='finished',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
